disabled_rules:
  - force_cast
  - function_body_length
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure
  - type_body_length
excluded:
  - Pods
switch_case_alignment:
  indented_cases: true
