name: CI
on: push

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SwiftLint
        run: ./Pods/SwiftLint/swiftlint
      - name: Try to autocorrect
        run: ./Pods/SwiftLint/swiftlint autocorrect
      - name: Check SwiftLint style
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "You have some swiftlint problems that can be autocorrected."
            echo "Please run `./Pods/SwiftLint/swiftlint autocorrect` before commit."
            exit 1
          else
            echo "Style is good!"
          fi
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: xcodebuild -scheme "Pods-Campus Density" -workspace "Campus Density.xcworkspace" -quiet clean build
